task: "20210208_1"
train_data: data/ratings_train.txt
val_data: data/ratings_val.txt
pretrained_word_vector: data/ko.bin
batch_size: 256
dropout_rate: 0.5
max_len: 70
filter_size: 100
kernel_sizes: [3, 4, 5]
max_pooling_kernel_size: 2
cnn_type: CNN-multichannel
log_dir: /workspace/exercise_book/logs/nsmc_pytorch
gpus: 8
distributed_backend: ddp